sattisite/urls.py
from django.conf.urls import url
from django.contrib import admin
from satti import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.main),
    url(r'^admin/', admin.site.urls),
    url(r'^chat/(?P<id>[0-9]{1,4})/', views.chat),
    url('^', include('django.contrib.auth.urls')),
    url(r'^signin/$', views.login),
    url(r'^signout/$', views.logout),
    url(r'^profile/(?P<username>\w+)/', views.profile),
    url(r'^chatroom/(?P<id>[0-9]{1,4})/', views.chatroom, name="chatroom-menu"),
    url(r'^image/(?P<username>\w+)/', views.image),
    url(r'^menu/', views.room_menu),
    url(r'^upload/', views.upload_image, name="upload-image"),
    url(r'^upload-chat/(?P<id>[0-9]{1,4})/', views.upload_chat_image, name="upload-chat-image"),
    url(r'^text/', views.change_profile_text, name="text"),
    url(r'^create/', views.create_chatroom, name="create-chatroom"),
    url(r'^new-room/', views.room_create_menu, name="room-create-menu"),
    url(r'^join-room/', views.room_join_menu, name="room-join-menu"),
    url(r'^join/(?P<id>[0-9]{1,4})/', views.join_chatroom, name="join-chatroom"),
    url(r'^leave/(?P<id>[0-9]{1,4})/', views.leave_chatroom, name="leave-chatroom"),
    url(r'^private/(?P<username>\w+)/', views.private_chat, name="private-chat"),
    url(r'^list/', views.chat_list_json, name="chat-list-json"),
    url(r'^info/(?P<id>[0-9]{1,4})/', views.chat_info_json, name="chat-info-json"),
    url(r'^chat-list-item/(?P<pk>[0-9]{1,4})/', views.render_chat_list_item, name="chat-list-item"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

satti/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.utils import timezone
from datetime import datetime

PROFILE_TEXT = "This is my profile text. Isn't it fun?"
CHATROOM_TEXT = "This is the default chatroom description. It is a bit longe"\
                "r than the default text for profiles, and that's intentional."
DEFAULT_IMAGE_PATH = "images/default.jpg"

class ChatRoom(models.Model):
	def __str__(self):
		return self.name

	name = models.CharField(max_length=100)
	image = models.ImageField(upload_to='images/', default=DEFAULT_IMAGE_PATH)
	max_users = models.PositiveSmallIntegerField(default=50)
	description = models.TextField(max_length=200, blank=True, default=CHATROOM_TEXT)
	created_at = models.DateTimeField(auto_now_add=True, editable=False)
	modified = models.DateTimeField(auto_now_add=True)
	creator = models.ForeignKey('ChatUser', null=True, related_name="created_rooms")
	admins = models.ManyToManyField('ChatUser', related_name="admin_in")
	is_private = models.BooleanField(default=False)
	users = models.ManyToManyField('ChatUser', related_name="user_in")
	users_online = models.ManyToManyField('ChatUser')
	banned = models.ManyToManyField('ChatUser', related_name="banned_in")

	def add_message(self):
		self.modified = timezone.now()
		self.save()

	def is_creator(self, chatuser):
		return self.creator == chatuser

	def is_admin(self, chatuser):
		return self.admins.filter(pk=chatuser.pk).exists()

	def set_admin(self, chatuser):
		self.admins.add(chatuser)

	def is_banned(self, chatuser):
		return self.banned.filter(pk=chatuser.pk).exists()

	def has_messages(self):
		return ChatMessage.objects.filter(room=self).exists()

	def latest_message(self):
		return ChatMessage.objects.filter(room=self).latest('created_at')

	def get_users_online(self):
		return self.users_online.count()

	def ban(self, chatuser):
		self.banned.add(chatuser)
		chatuser.chatrooms.remove(self)
		if chatuser in self.users.all():
			self.users.remove(chatuser)

	def get_banned(self, chatuser):
		return chatuser.banned_in(self).exists()


class ChatUser(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	chatrooms = models.ManyToManyField(ChatRoom, blank=True)
	image = models.ImageField(upload_to='images/', default=DEFAULT_IMAGE_PATH)
	profile_text = models.CharField(default=PROFILE_TEXT, max_length=200)
	contacts = models.ManyToManyField("self", blank=True, related_name="contacts")
	online = models.BooleanField(default=False)
	last_seen = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.user.username

	def connect(self):
		self.online = True

	def disconnect(self):
		self.online = False
		self.last_seen = timezone.now()

	def read(self, chatroom):
		messages = ChatMessage.objects.filter(room=chatroom).filter(read_by=self)
		for msg in messages:
			msg.set_read(self)

	"""
	Gets the last seen timestamp in as a string
	"""
	def get_last_seen(self):
		from .helpers import list_timestamp
		if self.last_seen is not None:
			return list_timestamp(self.last_seen)
		else: return "never"

class ChatMessage(models.Model):
	author = models.ForeignKey('ChatUser', blank=True, null=True)
	room = models.ForeignKey('ChatRoom')
	text = models.TextField(max_length = 1000)
	created_at = models.DateTimeField(auto_now_add=True)
	image = models.ImageField(blank=True)
	notification = models.BooleanField(default=False)
	read_by = models.ManyToManyField('ChatUser', related_name="has_read")

	def is_seen(self):
		return self.read_by.all().exists()

	def set_read(self, chatuser):
		self.read_by.add(chatuser)

satti/forms.py
from django import forms
from .models import ChatRoom

class ImageUploadForm(forms.Form):
	image = forms.ImageField()

class RoomCreationForm(forms.ModelForm):
	class Meta:
		model = ChatRoom
		fields = ['name', 'description']

templates/chat.html
{% load static %}
<script type="text/javascript">
$(document).ready(function() {


   {% for chatuser in users %}
   $(".{{ chatuser.user.username }}").click(function() {
      $.get("profile/{{ chatuser.user.username }}/", function(data) {
         $(".modal-content").html(data);
         $("#myModal").css("display", "block");
      })
   })
   {% endfor %}
});
</script>

   {% if messages.exists %}
   {% for message in messages %}
   {% if message.notification == True %}
   <li class="room-notify"><b>{{ message.text }}</b></li>
   {% else %}
   <li class="message">
      <span>
         <img src="/static/images/default.jpg" class="pointer {{ message.author }}"></span><span class="message-span">
         <div><h5 id="id_message_{{ message.pk }}">{{ message.text }}</h5></div>
         </span>
         <span class="timestamp">{{ message.created_at|date:"o-m-d H:i:s" }}</span>
         </li>
   {% endif %}
   {% endfor %}
   {% else %}
   <div class="text-center" id="no-messages-{{ id }}"><i>No messages yet!</i></div>
   {% endif %}

templates/chat_list_item.html
{% load static %}

<li class="pointer {% if chat.private %}private_{{ chat.name }}{% endif %}" id={{ chat.pk }}>
	<img class="thumb" src={% static "images/default.jpg" %}>
	<div class="chat-info">
		<h5><b>{{ chat.name }}</b>
		<span class="timestamp" id="id_timestamp_{{ chat.pk }}">{% if chat.has_msg %}{{ chat.last_msg_time }}{% endif %}</span></h5>
		<h6><span class="msg" id="latest{{ chat.pk }}">
		{% if chat.has_msg %}{% if chat.last_msg_author %}{{ chat.last_msg_author }}:{% endif %} {{ chat.last_msg_text }}
		{% else %}<i>no messages</i>
		{% endif %}</span>
		</h6>
	</div>	
</li>

templates/chatroom.html
{% load static %}
<button class="chat-menu-button button">More chatrooms</button>

<button class="button join" id="id_join_{{ pk }}">
{% if not in_room %}Join{% else %}Leave{% endif %}
</button>
<div class="chat-info-div">
	<div class="chat-info-upper">
		<div>
			<h1>{{ name }}</h1>
			<h6><i>Created by {{ creator }}</i></h6>
			<h6>{{ description }}</h6>
		</div>
		
		<div>
			<img src="{% static "images/default.jpg" %}">
			<!-- uploading images not implemented for now
			{% if is_admin == True or is_creator == True %}
			<form class="form-inline" id="image-form-chat" action="{% url 'upload-chat-image' chatroom.pk %}" method="post" enctype="multipart/form-data">{% csrf_token %}
			    <p>
			    	<div class="button-container-chatroom">
				        <input id="id_image_chatroom" type="file" class=button name="image">
				    </div>
			    </p>
			</form>			
			{% endif %}
		-->	
		</div>
		

	</div>

	<div class="chat-info-lower">
		<div class="chat-info-lower-left">
			<h4>Chat members</h4>
			<div class="chat-info-members">
			<ul>
				{% for user in users %}
				<li id="{{ chatroom.pk }}{{ user.user.username }}">
					<img src={% static "images/default.jpg" %}>
					{{ user.user.username }}
					{% if is_admin == True or is_creator == True%}
					{% if user.user != request.user %}
					<button class="button-ban tip" id="id_ban_{{ chatroom.pk }}_{{ user.pk }}">
					<span class="tooltiptext">Ban user</span>
					<img src="{% static 'images/trash.png' %}"></button>
					<button class="button-admin tip" id="id_admin_{{ chatroom.pk }}_{{ user.pk }}">
					<span class="tooltiptext">Make user admin</span>
					<img src="{% static 'images/star-grey.png'%}">
					</button>
					{% endif %}
					{% endif %}
				</li>
				{% endfor %}
			</ul>
			</div>
		</div>

		<div class="chat-info-lower-right">
			<h4>Statistics</h4>
			<ul>
				<li><h6>
						Members: <span class="value">{{ user_count }}</span>
						</h6></li>
				<li><h6>
						Created at: <span class="value">{{ created_at }}</span>
				</h6></li>
				<li><h6>
						Total messages: <span class="value">{{ message_count }}</span>
				</h6></li>
				<li><h6>
						Average messages per day: <span class="value">{{ avg_daily_msgs|floatformat }}</span>
				</h6></li>
			</ul>
		</div>
	</div>
</div>

<script type="text/javascript">

	$("#id_image_chatroom").change(function() {
		$("#image-form-chat").submit();

		$.get("/chatroom/"+"{{ pk }}/", function(data) {
			$(".modal-content").html(data);
		})
	})

	var prev1;
	$.get("/chatroom/"+"{{ pk }}/", function(data) {
		prev1 = data;
	})

	$(".chat-menu-button").click(function(e) {
		$.get("{% url 'room-join-menu' %}", function(data) {
			$(".modal-content").html(data);
		})
	})

	{% for user in users %}
	$("#{{ chatroom.pk }}{{ user.user.username }}").click(function() {
		$.get("profile/{{ user.user.username }}/", function(data) {
			$(".modal-content").html(data)
			$(".back-btn-modal-profile").css("display", "block")
			$(".back-btn-modal-profile").click(function(e) {
				$(".modal-content").html(prev1);
			})
		})
	})

	$("#id_ban_{{ pk }}_{{ user.pk }}").click(function(e) {
		sendRoomAction("ban", {{ pk }}, {{ user.pk }});
	})

	$("#id_admin_{{ pk }}_{{ user.pk }}").click(function(e) {
		sendRoomAction("admin", {{ pk }}, {{ user.pk }});
	})
	{% endfor %}

	$("#id_join_{{ pk }}").click(function() {
		{% if not in_room %}
		sendRoomAction("join", {{ pk }}, "")
		{% else %}
		sendRoomAction("leave", {{ pk }}, "")
		$("#myModal").css("display", "none");
		$("#{{ pk }}").remove();
		$("#chat_area").html(choose);
		$(".write-section").css("display", "none");
        $(".open-room-bar").css("display", "none");
		{% endif %}
		
		//this could be done better...
		setTimeout(function() {
			window.location.reload();
		}, 100);
	})
</script>

templates/create_chatroom.html
<div class="new-chat-div">
<h2>New chatroom</h2>
<form id="new-chat-form" enctype="multipart/form-data" action="/create/" method="post">
	{% csrf_token %}
	<table>	{{ form.as_table }}</table>
	<input type="submit" value="Create"/>
</form>
</div>

<script type="text/javascript">
	$("#id_description").focus(function(e) {
		$("#id_description").val("")
		$("#id_description").css("color", "black")
	})
	$("#new-chat-form").on('submit', function(e) {
		e.preventDefault();
		this.submit();
		setTimeout(function() {
			window.location.reload();
		}, 100);
		})
	
</script>

templates/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

	<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
	<title>Sätti</title>

</head>
<body>
<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery.dotdotdot.min.js" %}"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
{% include "templates/main.js" %}

	<nav class="nav-top">
			<div class="navbar-header">
				<div>Sätti</div>
			</div>
			<div class="navbar">
				<p>
					Signed in as
					<a id="profile">{{ request.user }}</a>
					<a href="/signout/">Logout</a>
				</p>
			</div>
	</nav>

	<div class="content">
		<div id="myModal" class="modal">
		<span class="close">&times;</span>
  		<!-- Modal content -->
	  		<div class="modal-content">
	  		</div>

		</div>
			<div class="menu" id="menu">
				<ul>
					{% if in_chats %}
					{% for chat in chats %}
					{% include "templates/chat_list_item.html" %}
					{% endfor %}
					{% else %}
					<div class="text-center"><i>You're not in any conversations yet! Join a chatroom or create your own?</i></div>
					{% endif %}
				</ul>
				<div class="room-actions">
					<button id="button-join-room" class="button">Join room</button>
					<button id="button-create-room" class="button">Create room</button>
				</div>
			</div>

			<div class="chat-area">
					<nav class="open-room-bar">
						<div class="bar-content">
							<div id="navbar">
							</div>
						</div>					
					</nav>


				<div class="message-section" id="chat_area">
					<div class="text-center" id="id_choose"><i>Choose a chat to start messaging!</i></div>
				</div>
				<div class="write-section">
					<textarea id="message_text"></textarea>
					<button class="button" id="send_button">Send</button>
				</div>
			</div>
	</div>
	<!-- The Modal -->


</body>


</html>

templates/join_chatroom.html
{% load static %}
<div class="join-room">
	<div class="join-room-bar">
		<div class="heading">
			<h2>Joinable chatrooms</h2>
			<h6>Click on a room name to see info and join</h6>
		</div>
	</div>
	{% if joinable_rooms %}
	<div class="joinable-list">
	<ul>
		{% for room in joinable_rooms %}
		<li id="joinable-{{ room.pk }}"><img src="{% static "images/default.jpg" %}">{{ room.name }}</li>
		{% endfor %}
	</ul>
	</div>
	{% else %}
	<div class="text-center">
	<i>Whoops! Looks like you have already joined all the possible rooms.</i>
	</div>
	<ul>
	{% endif %}
</div>

<script type="text/javascript">
	{% for room in joinable_rooms %}
	$("#joinable-{{ room.pk }}").click(function() {
		prev = $(".modal-content").html()
		$.get(window.location.href + 'chatroom/{{ room.pk }}/', function(data) {
			$(".modal-content").html(data);
			$(".back-btn-modal-chatroom").css("display", "block")
			$(".back-btn-modal-chatroom").click(function(e) {
				$(".modal-content").html(prev);
			})
		})
	})
	{% endfor %}
</script>

templates/new_chat.html
{% load static %}
<script type="text/javascript">
$(document).ready(function() {


   {% for chatuser in users %}
   $(".{{ chatuser.user.username }}").click(function() {
      $.get("profile/{{ chatuser.user.username }}/", function(data) {
         $(".modal-content").html(data);
         $("#myModal").css("display", "block");
      })
   })
   {% endfor %}
});
</script>

   {% if messages.exists %}
   {% for message in messages %}
   {% if message.notification == True %}
   <li class="room-notify"><b>{{ message.text }}</b></li>
   {% else %}
   <li class="message">
      <span>
         <img src="/image/{{ message.author }}/ " class="pointer {{ message.author }}"></span><span class="message-span">
         <div><h5 id="id_message_{{ message.pk }}">{{ message.text }}</h5></div>
         </span>
         <span class="timestamp">{{ message.created_at|date:"o-m-d H:i:s" }}</span>
         </li>
   {% endif %}
   {% endfor %}
   {% else %}
   <div class="text-center" id="no-messages-{{ id }}"><i>No messages yet!</i></div>
   {% endif %}

templates/new_chatroom.html
<input id="chat-name-input" type="text" value="Enter chat name here..."> 

templates/newest_index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

	<link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
	<title>Että näin</title>

</head>
<body>
<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/jquery.dotdotdot.min.js" %}"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
{% include "templates/main.js" %}

	<nav class="nav-top">
			<div class="navbar-header">
				<div>Sätti</div>
			</div>
			<div class="navbar">
				<p>
					Signed in as
					<a id="profile">{{ request.user }}</a>
					<a href="/signout/">Logout</a>
				</p>
			</div>
	</nav>

	<div class="content">
		<div id="myModal" class="modal">
		<span class="close">&times;</span>
  		<!-- Modal content -->
	  		<div class="modal-content">
	  		</div>

		</div>
			<div class="menu" id="menu">
				<ul>
					{% if in_chats %}
					{% for chat in chats %}
					{% include "templates/chat_list_item.html" %}
					{% endfor %}
					{% else %}
					<div class="text-center"><i>You're not in any conversations yet! Join a chatroom or create your own?</i></div>
					{% endif %}
				</ul>
				<div class="room-actions">
					<button id="button-join-room" class="button">Join room</button>
					<button id="button-create-room" class="button">Create room</button>
				</div>
			</div>

			<div class="chat-area">
					<nav class="open-room-bar">
						<div class="bar-content">
							<div id="navbar">
							</div>
						</div>					
					</nav>


				<div class="message-section" id="chat_area">
					<div class="text-center" id="id_choose"><i>Choose a chat to start messaging!</i></div>
				</div>
				<div class="write-section">
					<textarea id="message_text"></textarea>
					<button class="button" id="send_button">Send</button>
				</div>
			</div>
	</div>
	<!-- The Modal -->


</body>


</html>

templates/profile.html
{% load static %}

<img class="back-btn-modal-profile back-btn-modal" src="{% static "images/back.png" %}">

<div class="profile-content">
	{% if not request.user.username == username %}
	<button id="id_private_{{ username }}" class="join-button">Message</button>
	{% endif %}
	<div class="profile-image">
		<img src="{% static "images/default.jpg" %}">
		<!-- Uploading images not implemented for now

		{% if chatuser.user == request.user %}
		<form class="form-inline" id="image-form" action="{% url 'upload-image' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
		    <p>
		    	<div class="button-container">
			        <input id="id_image" type="file" class=button name="image">
			    </div>
		    </p>
		</form>
		{% endif %}
		
		-->
	</div>
	<div class="profile-username">
		<h1>{{ chatuser.user.username }}</h1>
	</div>
	
	<div class="profile-text">
			
				{% if chatuser.user == request.user %}
				<form class="form-inline" id="text-form" action="{% url 'text' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
					<textarea id="text-input" name="text" form="text-form">{{ chatuser.profile_text }}</textarea>
				</form>
					{% else %}
		<h4 id="h4-text">{{ chatuser.profile_text }}</h4>
		{% endif %}
	</div>

</div>

<script>

	$("#text-input").width($("#h4-text").width())
	$("#text-input").height($("#h4-text").height())

	$("#id_image").change(function() {
		$("#image-form").submit()
		$.get(window.location.href
		 + "profile/" + '{{ request.user.username }}' 
		 + "/", function(data) {
		 		$(".modal-content").html(data);
		 })

		})
	$(document).keypress(function(e) {
		if(e.which==13) {
			e.preventDefault()
			$("#text-form").submit()
			}
		})

	$("#id_private_{{ username }}").click(function() {
		$.get("{% url 'private-chat' username=username %}")
		setTimeout(function() {
			window.location.reload();
		}, 10);
	})
</script>

templates/room_menu.html
{% load static %}
<ul>
	{% for room in rooms %}
	<li id={{ room.pk }}>
		<img class="menu-thumb" src="{% static "images/default.jpg" %}" alt="">
		<div class="chat-info">
			<h5><b>{{ room.name }}</b><span class="timestamp">{{ room.latest_message.created_at }}</span></h5>
			<h6><span class="msg">{{ room.latest_message.author }}:{{ room.latest_message.text }}</span></h6>
		</div>	
	</li>
	{% endfor %}
</ul>